<?php if ($this->pageCount): ?>

<nav>
<ul class="pagination">

<!-- Previous page link -->
<li class="page-item <?= (!isset($this->previous)) ? "disabled" : "" ?>">
  <a class="page-link" href="<?= (isset($this->previous)) ? $this->url($this->route, [], ['query'=>['page'=>$this->previous]]) : "" ?>" aria-label="Previous">
    <span aria-hidden="true">&laquo;</span>
  </a>
</li>  

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
    <li class="page-item <?= ($page === $this->current) ? "active" : "" ?>">
        <a class="page-link" href="<?= $this->url($this->route, [], ['query'=>['page'=>$page]]); ?>"><?= $this->escapeHtml($page).($page === $this->current ? " <span class='sr-only'>(current)</span>" : '') ?></a>
    </li> 
<?php endforeach; ?>

<!-- Next page link -->
<li class="page-item <?= (!isset($this->next)) ? "disabled" : "" ?>">
  <a class="page-link" href="<?= (isset($this->next)) ? $this->url($this->route, [], ['query'=>['page'=> $this->next]]) : "" ?>" aria-label="Next">
    <span aria-hidden="true">&raquo;</span>
  </a>
</li>  
</ul>
</nav>
<?php endif; ?>